name: "Hello World after remove draft"

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  hello:
    if: |
      github.event.pull_request.merged == true
      && !contains(github.event.pull_request.labels.*.name, 'skip-push')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo "remove-draft: ${{ contains(github.event.pull_request.labels.*.name, 'remove-draft') }}"
          echo "Hello World!"