name: "Hello World after remove draft"

on:
  workflow_run:
    workflows:
      - remove-draft
    types:
      - completed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"