name: "Hello World after remove draft"

on:
  workflow_run:
    workflows:
      - "Remove 'draft: true' from changed files"
    types:
      - completed

jobs:
  hello:
    if: |
      github.event.pull_request.merged == true
      && !contains(github.event.pull_request.labels.*.name, 'skip-push')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"