name: "Remove 'draft: true' from changed files"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove-draft:
    if: |
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files from PR
        id: changed_files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' > changed_files.txt
          cat changed_files.txt

      - name: |
          Remove 'draft: true' from changed files
        run: |
          while read file; do
            if [ -f "$file" ] && grep -q 'draft: true' "$file"; then
              echo "Remove 'draft: true' from $file"
              sed -i '/draft: true/d' "$file"
            fi
          done < changed_files.txt
          rm changed_files.txt

      - name: Create pull request
        uses: actions/checkout@v4
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add .
          git commit -m "approveされたのでDraft: trueを削除しました"
          git push