name: "Remove 'draft: true' from changed files when PR is approved"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove-draft:
    if: |
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get changed files from PR
        id: changed_files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' > changed_files.txt
          cat changed_files.txt

      - name: |
          Remove 'draft: true' from changed files
        run: |
          while read file; do
            if [ -f "$file" ] && [[ "$file" == *.md ]] && grep -q '^Draft: true$' "$file"; then
              echo "Remove 'Draft: true' from $file"
              sed -i '/^Draft: true$/d' "$file"
            fi
          done < changed_files.txt
          rm changed_files.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          if git diff --exit-code --quiet; then
            echo "変更がありません。コミットとプッシュはスキップします。"
          else
            # 変更されたファイルをステージングします。
            git add .
            git commit -m "feat: PRが承認されたため、'draft: true' を削除しました"
            git push origin HEAD
            echo "変更がコミットされ、プッシュされました。"
          fi